#!/bin/bash
# ------------------
# setup_test_env.sh
# ------------------
# Extracts the CWS server distribution archive and sets up the environment
# for running Maven tests against it later.

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${ROOT}/utils.sh

SERVER_DIST='cws_server.tar.gz'
DIST=${ROOT}/dist
CWS=${DIST}/cws
TEST_ENV_DIR=${DIST}/test-env

# Parse command line arguments
CLEAN_EXISTING=true

while [[ $# -gt 0 ]]; do
  case $1 in
    --no-clean)
      CLEAN_EXISTING=false
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--no-clean]"
      exit 1
      ;;
  esac
done

# Check if distribution archive exists
if [[ ! -f ${DIST}/${SERVER_DIST} ]]; then
  print "ERROR: Server distribution archive not found at ${DIST}/${SERVER_DIST}"
  print "Please run create_server_dist.sh first to create the server distribution."
  exit 1
fi

# Clean previous environment if requested
if [[ "$CLEAN_EXISTING" = true ]]; then
  print "Cleaning previous test environment..."
  rm -rf ${TEST_ENV_DIR}
fi

# Create test environment directory
print "Creating test environment directory..."
mkdir -p ${TEST_ENV_DIR}

# Extract the server distribution
print "Extracting server distribution from ${DIST}/${SERVER_DIST}..."
tar -xzf ${DIST}/${SERVER_DIST} -C ${TEST_ENV_DIR}

if [[ $? -ne 0 ]]; then
  print "ERROR: Failed to extract server distribution."
  exit 1
fi

# Create environment setup script for tests
print "Creating environment setup script for tests..."
cat > ${TEST_ENV_DIR}/setup_maven_env.sh << EOF
#!/bin/bash
# Generated by setup_test_env.sh

# This script sets up the environment variables needed for Maven tests
# Source this script before running Maven tests: source ./setup_maven_env.sh

export CWS_TEST_ROOT="${TEST_ENV_DIR}/cws"
export CWS_TEST_TOMCAT_DIR="\${CWS_TEST_ROOT}/server/apache-tomcat-${TOMCAT_VER}"
export CWS_TEST_LIB_DIR="\${CWS_TEST_TOMCAT_DIR}/lib"
export CWS_TEST_WEBAPPS_DIR="\${CWS_TEST_TOMCAT_DIR}/webapps"

# These environment variables can be used in your Maven tests
# by referencing them from pom.xml or with -D parameters
echo "CWS test environment set up at \${CWS_TEST_ROOT}"
echo "To run Maven tests against this environment:"
echo "  mvn test -Dcws.test.root=\${CWS_TEST_ROOT} -Dcws.test.lib=\${CWS_TEST_LIB_DIR}"
EOF

chmod +x ${TEST_ENV_DIR}/setup_maven_env.sh

print "Test environment setup completed successfully."
print "To prepare for running Maven tests:"
print "  1. cd ${TEST_ENV_DIR}"
print "  2. source ./setup_maven_env.sh"
print "  3. Run Maven tests with appropriate parameters"
print "     Example: mvn test -Dcws.test.root=\$CWS_TEST_ROOT -Dcws.test.lib=\$CWS_TEST_LIB_DIR"