#!/bin/bash
# ------------------
# setup_test_env.sh
# ------------------
# Extracts the CWS server distribution archive and sets up the environment
# for running Maven tests against the extracted server build.
# This script directly configures the Maven test environment without requiring
# a separate source step, making it suitable for CI pipelines.

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${ROOT}/utils.sh

SERVER_DIST='cws_server.tar.gz'
# DIST=${ROOT}/dist
CWS=${ROOT}/cws
TEST_ENV_DIR=${ROOT}/test-env

# Parse command line arguments
CLEAN_EXISTING=true
CREATE_MAVEN_SETTINGS=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --no-clean)
      CLEAN_EXISTING=false
      shift
      ;;
    --maven-settings)
      CREATE_MAVEN_SETTINGS=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--no-clean] [--maven-settings]"
      exit 1
      ;;
  esac
done

# Check if distribution archive exists
if [[ ! -f ${ROOT}/${SERVER_DIST} ]]; then
  print "ERROR: Server distribution archive not found at ${ROOT}/${SERVER_DIST}"
  print "Please run create_server_dist.sh first to create the server distribution."
  exit 1
fi

# Clean previous environment if requested
if [[ "$CLEAN_EXISTING" = true ]]; then
  print "Cleaning previous test environment..."
  rm -rf ${TEST_ENV_DIR}
fi

# Create test environment directory
print "Creating test environment directory..."
mkdir -p ${TEST_ENV_DIR}

# Extract the server distribution
print "Extracting server distribution from ${ROOT}/${SERVER_DIST}..."
tar -xzf ${ROOT}/${SERVER_DIST} -C ${TEST_ENV_DIR}

if [[ $? -ne 0 ]]; then
  print "ERROR: Failed to extract server distribution."
  exit 1
fi

# Define test environment variables
CWS_TEST_ROOT="${TEST_ENV_DIR}/cws"
CWS_TEST_TOMCAT_DIR="${CWS_TEST_ROOT}/server/apache-tomcat-${TOMCAT_VER}"
CWS_TEST_LIB_DIR="${CWS_TEST_TOMCAT_DIR}/lib"
CWS_TEST_WEBAPPS_DIR="${CWS_TEST_TOMCAT_DIR}/webapps"

# Create a Maven settings file if requested
if [[ "$CREATE_MAVEN_SETTINGS" = true ]]; then
  print "Creating Maven settings file..."
  
  # Create a Maven settings file that includes the test classpath
  MAVEN_SETTINGS_DIR="${TEST_ENV_DIR}/maven"
  mkdir -p ${MAVEN_SETTINGS_DIR}
  
  cat > ${MAVEN_SETTINGS_DIR}/settings.xml << EOF
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <profiles>
    <profile>
      <id>cws-test-env</id>
      <properties>
        <cws.test.root>${CWS_TEST_ROOT}</cws.test.root>
        <cws.test.lib>${CWS_TEST_LIB_DIR}</cws.test.lib>
        <cws.test.webapps>${CWS_TEST_WEBAPPS_DIR}</cws.test.webapps>
      </properties>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>cws-test-env</activeProfile>
  </activeProfiles>
</settings>
EOF
  
  print "Maven settings created at ${MAVEN_SETTINGS_DIR}/settings.xml"
  print "Use with: mvn -s ${MAVEN_SETTINGS_DIR}/settings.xml test"
fi

# Create properties file with test environment information
print "Creating test environment properties file..."

cat > ${TEST_ENV_DIR}/cws-test-env.properties << EOF
# CWS Test Environment Properties
# Generated by setup_test_env.sh

cws.test.root=${CWS_TEST_ROOT}
cws.test.tomcat=${CWS_TEST_TOMCAT_DIR}
cws.test.lib=${CWS_TEST_LIB_DIR}
cws.test.webapps=${CWS_TEST_WEBAPPS_DIR}
EOF

# Create a script to set environment variables for interactive use
print "Creating environment setup script for interactive use..."

cat > ${TEST_ENV_DIR}/setup_env.sh << EOF
#!/bin/bash
# Generated by setup_test_env.sh

# This script sets up the environment variables needed for Maven tests
# Source this script before running Maven tests: source ./setup_env.sh

export CWS_TEST_ROOT="${CWS_TEST_ROOT}"
export CWS_TEST_TOMCAT_DIR="${CWS_TEST_TOMCAT_DIR}"
export CWS_TEST_LIB_DIR="${CWS_TEST_LIB_DIR}"
export CWS_TEST_WEBAPPS_DIR="${CWS_TEST_WEBAPPS_DIR}"

echo "CWS test environment set up at \${CWS_TEST_ROOT}"
echo "To run Maven tests against this environment:"
echo "  mvn test -Dcws.test.root=\${CWS_TEST_ROOT} -Dcws.test.lib=\${CWS_TEST_LIB_DIR}"
EOF

chmod +x ${TEST_ENV_DIR}/setup_env.sh

# Output Maven command-line settings for direct use in CI
print "Generating Maven system properties for CI use..."

MVN_PROPS="-Dcws.test.root=${CWS_TEST_ROOT} -Dcws.test.lib=${CWS_TEST_LIB_DIR} -Dcws.test.webapps=${CWS_TEST_WEBAPPS_DIR}"
echo "${MVN_PROPS}" > ${TEST_ENV_DIR}/maven-props.txt

# Output the configuration for immediate use
print "Test environment setup completed successfully."
print "Environment configured with:"
print "  CWS_TEST_ROOT=${CWS_TEST_ROOT}"
print "  CWS_TEST_TOMCAT_DIR=${CWS_TEST_TOMCAT_DIR}"
print "  CWS_TEST_LIB_DIR=${CWS_TEST_LIB_DIR}"
print ""
print "For CI/CD pipelines, use these Maven system properties:"
print "  ${MVN_PROPS}"
print ""
print "For interactive use:"
print "  source ${TEST_ENV_DIR}/setup_env.sh"