# CWS CONFIGURATION
#
# DO NOT MANUALLY EDIT THIS FILE!
#
# THIS FILE WILL GET OVERWRITTEN AT CONFIGURE TIME,
# BEFORE CWS STARTS UP FOR THE FIRST TIME
#

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
