#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $ROOT
AUTO_DELETE_DIR=$1

echo "destroying created AWS resources ..."

#
# RUN TERRAFORM DESTROY 
#
terraform destroy -auto-approve

if [[ $AUTO_DELETE_DIR =~ ^(y|Y)$ ]]
then
    WORK_DIR=`pwd`
    echo "Deleting working directory: ${WORK_DIR}..."
    cd ..
    rm -rf ${WORK_DIR}
    echo "Deleted working directory: ${WORK_DIR}."
    exit 0 
fi

#
# NOW THAT DESTROY IS COMPLETE,
# ASK THE USER IF THEY WANT TO DELETE THE WORKING DIRECTORY
#
echo "If the above line says \"Destroy complete!\" you are probably done with this working directory, and it should be deleted."
while [[ ! $REPLY =~ ^(y|Y|n|N)$ ]]; do
read -p "Delete this working directory (`pwd`)? (Y/N): " REPLY
	if [[ $REPLY =~ ^(n|N)$ ]]
	then
		break
	fi
	
	if [[ $REPLY =~ ^(y|Y)$ ]]
	then
		WORK_DIR=`pwd`
		echo "Deleting working directory: ${WORK_DIR}..."
		cd ..
		rm -rf ${WORK_DIR}
		echo "Deleted working directory: ${WORK_DIR}."
		break
	fi

	printf "  ERROR: Must specify either 'Y' or 'N'.\n\n";
done

