name: Camunda Docker

on:
  workflow_run:
    workflows: ["CI Base"] # Name of the workflow that must complete first
    types:
      - completed

jobs:
  run-after-ci-base:
    runs-on: ubuntu-latest
    # Only run this job if the triggering workflow (CI Base) was successful
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch the specific commit that triggered the 'CI Base' workflow
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Placeholder Step
        run: |
          echo "CI Base workflow completed successfully."
          echo "Running Camunda Docker workflow steps..."
          echo "Commit SHA: ${{ github.event.workflow_run.head_sha }}"
          # Add actual steps for this workflow here later

# Add more jobs for this workflow as needed
